# Generated by Django 2.1.3 on 2018-12-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(verbose_name='試合日時')),
                ('venue', models.CharField(blank=True, max_length=20, null=True)),
                ('weather', models.CharField(blank=True, max_length=10, null=True)),
                ('my_team', models.CharField(blank=True, max_length=20, null=True)),
                ('opponent_team', models.CharField(blank=True, max_length=20, null=True)),
                ('my_score', models.IntegerField(blank=True, null=True)),
                ('opponent_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
