# Generated by Django 2.1.3 on 2019-01-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbrecord', '0004_auto_20190112_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='my_inning_score',
            new_name='bot_inning_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='my_score',
            new_name='bot_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='my_team',
            new_name='bot_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opponent_inning_score',
            new_name='top_inning_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opponent_score',
            new_name='top_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opponent_team',
            new_name='top_team',
        ),
    ]
