# Generated by Django 2.1.3 on 2019-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbrecord', '0005_auto_20190118_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
