# Generated by Django 2.1.3 on 2019-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbrecord', '0006_auto_20190127_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='weather',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
