# Generated by Django 2.1.3 on 2019-01-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbrecord', '0008_game_sayonara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='sayonara',
            new_name='x_flag',
        ),
    ]
